config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('reservation/', include('reservations.urls', namespace='reservations')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from pages.views import HomePageView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

reservations/urls.py
from django.urls import path

from reservations.views import ReserveView

app_name = 'reservations'

urlpatterns = [
    path('reserve/', ReserveView.as_view(), name='reserve'),
]

pages/models.py
from django.db import models


class ScrollModel(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='scroll')
    discount = models.PositiveIntegerField(default=0)
    description = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Discount Products'
        verbose_name = 'Discount Product'

products/models.py
from django.db import models


class CategoryModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'
        verbose_name = 'Category'


class ProductModel(models.Model):
    name = models.CharField(max_length=128)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE, related_name='products')
    image = models.ImageField(upload_to='products')
    description = models.TextField(default='')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Products'
        verbose_name = 'Product'

reservations/models.py
from django.db import models


class ReservationModel(models.Model):
    full_name = models.CharField(max_length=128)
    email = models.EmailField()
    phone_number = models.CharField(max_length=13)
    date = models.DateField()
    time = models.TextField()
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

    def __repr__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Reservation'
        verbose_name_plural = 'Reservations'

reservations/forms.py
from django import forms

from reservations.models import ReservationModel


class ReservationForm(forms.ModelForm):
    class Meta:
        model = ReservationModel
        fields = '__all__'

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from pages.models import ScrollModel
from products.models import ProductModel


class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        pizza = ProductModel.objects.filter(category__name='Pizza')
        burgers = ProductModel.objects.filter(category__name='Burgers')
        salad = ProductModel.objects.filter(category__name='Salad')
        fries = ProductModel.objects.filter(category__name='Fries')
        drinks = ProductModel.objects.filter(category__name='Drinks')
        discount_products = ScrollModel.objects.all()[:5]
        context = {
            'pizza': pizza,
            'burgers': burgers,
            'salad': salad,
            'fries': fries,
            'drinks': drinks,
            'discount_products': discount_products
        }
        return context

products/views.py
from django.shortcuts import render

reservations/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from reservations.forms import ReservationForm
from datetime import datetime


class ReserveView(CreateView):
    template_name = 'reservation.html'
    form_class = ReservationForm

    def get_success_url(self):
        return reverse_lazy('pages:home')

    def form_valid(self, form):
        reservation = form.save(commit=False)
        data = form.cleaned_data

        date = str(data.get('date')).split('-')[::1]
        date = '-'.join(date)
        date = datetime.strptime(date, '%Y-%m-%d')
        reservation.date = date

        reservation.save()
        return render(self.request, 'success.html')

    def form_invalid(self, form):
        print(form.errors)
        print(str(form.cleaned_data.get('date')))
        return render(self.request, 'form-errors.html', {'form': form})

templates/form-errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>You're form is valid!</h1>
{{ form.errors }}
</body>
</html>

templates/reservation.html
<div class="fixed_layer section" id="reservation">
            <div class="fixed_layer_padd container">
                <div class="row">
                    <div class="col-md-offset-6 col-md-6" data-aos="fade-down">
                        <div class="reserv_box">
                            <h1 class="section-title title_sty1">online reservation</h1>
                            <p class="short">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                            <form id="reserv_form" method="post" action="{% url 'reservations:reserve' %}">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group form_pos">
                                            <input type="text" name="full_name" required="" placeholder="Your name" class="form-control" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your name'" />
                                            <span class="form_icon"></span>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group form_pos">
                                            <input type="email" name="email" required="" placeholder="Your email" class="form-control" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your email'" />
                                            <span class="form_icon"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="form-group form_pos">
                                            <input type="text" name="phone_number" required="" placeholder="Phone" class="form-control" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Phone'" />
                                            <span class="form_icon"></span>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group form_pos">
                                            <input type="text" name="date" required="" placeholder="Date" class="form-control" id="reserv_date" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Date'" />
                                            <span class="form_icon"></span>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group form_pos">
                                            <input type="text" name="time" required="" placeholder="Time" class="form-control" id="reserv_time" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Time'" />
                                            <span class="form_icon"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <textarea rows="3" name="message" placeholder="Message" class="form-control" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Message'"></textarea>
                                </div>
                                <input type="submit" name="send" value="book now" class="btn btn-block" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Successfully reserved</h1>
</body>
</html>